name: entity_sync
version: '0.0.1'
description: An entity sync library for Dart developers.
homepage: https://github.com/cmberryau/entity_sync

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  moor: ^4.1.0
  shared_preferences: ^0.5.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  mockito: 5.0.3
  build_runner: ^1.10.1
  moor_generator: ^4.2.1
#  entity_sync_generator:
#    git:
#      url: https://github.com/lodlaw/entity_sync_generator
#      ref: dependencies-upgrade
